apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-terraform-resource
  namespace: flux-terraform
spec:
  interval: 30s
  url: https://github.com/vimuchiaroni/flux-terraform-azure
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: my-terraform-resource
  namespace: flux-terraform
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./terraform/azure/storage-account
  sourceRef:
    kind: GitRepository
    name: my-terraform-resource
  runnerPodTemplate:
    spec:
      image: docker.io/vimuchiaroni/tf-az-cli:1.0
      env:
        - name: ARM_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: azure-auth
              key: ARM_SUBSCRIPTION_ID
        - name: ARM_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-auth
              key: AZURE_CLIENT_ID
        - name: ARM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-auth
              key: AZURE_CLIENT_SECRET
        - name: ARM_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-auth
              key: AZURE_TENANT_ID
